### ISSUE TITLE
Different CUDA versions than PyTorch

### ISSUE THREAD

**Issue by hagianga21** [rusty1s/pytorch_sparse#122]
I got the problem when trying to install torch geometric:
```
RuntimeError: Detected that PyTorch and torch_sparse were compiled with different CUDA versions. PyTorch has CUDA version 11.1 and torch_sparse has CUDA version 11.2. Please reinstall the torch_sparse that matches your PyTorch install.
```
Could you please help me to solve it?

**Comment by rusty1s** [comment]
How did you try to install `pytorch_sparse`? Installing the `cu102` wheel should fix this problem.

**Comment by hagianga21** [comment]
Yes, I did it, but don't know why the error appears, the command I tried:
```
pip install torch-scatter -f https://pytorch-geometric.com/whl/torch-1.8.0+${cu111}.html
pip install torch-sparse -f https://pytorch-geometric.com/whl/torch-1.8.0+${cu111}.html
pip install torch-cluster -f https://pytorch-geometric.com/whl/torch-1.8.0+${cu111}.html
pip install torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.8.0+${cu111}.html
pip install torch-geometric
```

**Comment by rusty1s** [comment]
I see. I guess you have a system-wide CUDA 11.2 installation, which is used to load the extension. In order to change that, you need to link your system to the CUDA installation provided by PyTorch, i.e. the `cudatoolkit` that gets additionally installed when installing PyTorch via conda.

Mine is located in `{miniconda_path}/lib` and should contain files such as `libtorchsparse.so`. You can link to this specfic `cudatoolkit` via:
```
export LD_LIBRARY_PATH={miniconda_path}/lib:$LD_LIBRARY_PATH
```
