### ISSUE TITLE
What is the difference between `sample` and `sample_adj` function? 

### ISSUE THREAD

**Issue by deepakagrawal** [rusty1s/pytorch_sparse#153]
I am trying to understand the difference between the two functions. Besides the fact that `sample_adj` imports c function. I am seeing different samples resulting from these two functions. The shape of the resulting sampled node index is also not the same from these two functions.

**Comment by rusty1s** [comment]
I'm sorry for the messy naming and missing documentation. Those functions are mainly used internally in PyTorch Geometric.

1. `sample_adj` is used in the `NeighborSampler` class of PyTorch Geometric, and it will return a new `SparseTensor` in which `num_neighbors` nodes are sampled for each node in `subset`.
2. I think `sample` is mostly an artifact and not longer used. It basically returns modified destination node indices, so that every node in `subset` will have exactly `num_neighbors`.

**Comment by deepakagrawal** [comment]
Thank you for creating this library it's really helpful. That's alright. I am just trying to understand and hopefully, I can contribute and create the weighted version of the `sample` function. 

1. if `sample_adj` samples `num_neighbors` nodes for each node in `subset` then shouldn't the `n_id` (which is the output of `sample_adj` ) shape be = `[subset.shape[0], num_neighbors]`?.  
2.  What does `size = -1` mean for this function?
3. `sample` function is used in some of the examples like `MetaPath2Vec` class of Pytorch Geometric and the output of that has a shape of `[subset.shape[0], num_neighbor]`

**Comment by rusty1s** [comment]
I recently pushed some code for sampling with and without replacement, supporting both uniform and weighted sampling, see [here](https://github.com/rusty1s/pytorch_sparse/blob/master/csrc/cpu/utils.h#L28-L64). It's probably the easiest way to just replace the functionality in `sample_cpu.cpp` for sampling with this newly introduced `choice` function.
