### ISSUE TITLE
Building pytorch_sparse on conda-forge

### ISSUE THREAD

**Issue by mikemhenry** [rusty1s/pytorch_sparse#234]
:wave: 
I'm working on getting pytorch_sparse v0.6.13 onto conda-forge with PR https://github.com/conda-forge/pytorch_sparse-feedstock/pull/40 and I'm running into this error for some of the builds:

```
File "/home/conda/feedstock_root/build_artifacts/pytorch_sparse_1653761996216/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1626, in _get_cuda_arch_flags
arch_list[-1] += '+PTX'
IndexError: list index out of range
```

Any ideas what could be causing this? This is how setup.py is invoked: https://github.com/conda-forge/pytorch_sparse-feedstock/blob/main/recipe/meta.yaml#L17-L20

Thanks!

**Comment by rusty1s** [comment]
I think this is caused by PyTorch directly, see https://github.com/pytorch/pytorch/blob/master/torch/utils/cpp_extension.py#L1675-L1694. One thing you could try is specifying the `TORCH_CUDA_ARCH_LIST` by yourself: https://github.com/pytorch/pytorch/blob/master/torch/utils/cpp_extension.py#L948-L952.

**Comment by mikemhenry** [comment]
Thanks! I did not look close enough on that traceback! I will look into that, I set the cuda arch list manually in other packages so that should be very doable.
