### ISSUE TITLE
Difference about torch_sparse.spmm and torch.spmm

### ISSUE THREAD

**Issue by CXX1113** [rusty1s/pytorch_sparse#339]
What's difference about torch_sparse.spmm and torch.spmm?

**Comment by rusty1s** [comment]
There no longer exists a real difference since PyTorch integrated most of this package into its core by now. The most significant difference between the two right now is that `torch_sparse.SparseTensor` caches both CSR and CSC representations, which makes the backward pass of
```python
adj = SparseTensor(...)
x = torch.randn(x)
out = adj @ x
```
very efficient, while PyTorch needs to transpose the sparse matrix every time for this.

**Comment by CXX1113** [comment]
I see. Thank you!
