### ISSUE TITLE
Is there a roadmap of this library? 

### ISSUE THREAD

**Issue by bwdeng20** [rusty1s/pytorch_sparse#43]
Hi, rusty1s! 

Thx for your excellent works! I've noticed that there are some updates of this lib attempting to build more built-in interfaces like those provided in pytorch.  May I have your future plan of improving this lib. In particular, I'am curious about that will the features below be supported in the future?

1. High-dimensional sparse tensor and the corresponding operations, e.g., batched sparse tensor matmul. 
2. Broadcasting semantics for sparse tensors.
3. A concise sparse tensor class just like torch.sparse_coo_tensor.
4. (advanced) index and slice operations like what are supported by scipy.sparse module, though scipy.sparse.coo_matrix dose not support index and slice.

The features mentioned above may not be clear, just give me a rough reply. Last but not least, will the lib be merged into pytorch? I've subscribed two issues about sparse tensors in pytorch, but it seems there are almostly no progress and new discussions.

Thx again, have a good day!

**Comment by rusty1s** [comment]
Hi and thanks for your interest. I am heavily working on improving `torch-sparse` and a lot of its functionalities are currently still hidden to the user. I will change that in the near future. In the meantime, you need to look at the code directly.

1. Batched sparse matrices will likely be not supported, but sparse matrix multiplications with batched dense matrices already are, *e.g.* `sparse_mat @ dense_mat` where `sparse_mat` is a sparse tensor of shape [N, M]` and `dense_mat` is a tensor of shape `[batch_size, M, K]`.
2. Not sure what you exactly mean by this.
3. It is, see `SparseTensor`
4. Already supported.

Yeah, PyTorch has nearly no progress in making sparse support better, and that is one of the reasons why I built this library in the first place. However, it will likely not be merged into PyTorch since I need an extendable sparse format to incorporate new Graph Neural Network ideas. However, some features might.

Best,
Matthias

**Comment by bwdeng20** [comment]
Thanks for your quick response.  About the first two points.
1. I've tried to do  what you described earlier. The `sparse_mat @ batched_dense_mat`  and `sparse_mat @ dense_mat` failed.  However, other methods of `torch_sparse.tensor.SparseTensor` work well, including the slice and index tools!
``` python3
from scipy.sparse import coo_matrix
import torch as th
import torch_sparse as ts
import numpy as np

n=3
a=np.arange(1,n**2+1).reshape(n,n)
spa_sci=coo_matrix(a)
spa_ts=ts.tensor.SparseTensor.from_scipy(spa_sci)
# print(spa_ts)
#SparseTensor(row=tensor([0, 0, 0, 1, 1, 1, 2, 2, 2]),
#              col=tensor([0, 1, 2, 0, 1, 2, 0, 1, 2]),
#              val=tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32),
#              size=(3, 3), nnz=9, density=100.00%)
dm = th.ones(n,n)
bdm=dm[None,...].repeat(2,1,1)
# print(bdm)
# tensor([[[1., 1., 1.],
#          [1., 1., 1.],
#          [1., 1., 1.]],
#         [[1., 1., 1.],
#          [1., 1., 1.],
#          [1., 1., 1.]]])
spa_ts @ bdm
RuntimeError: expected scalar type Float but found Int (data_ptr at C:\tools\miniconda3\envs\test\lib\site-packages\torch\include\ATen/core/TensorMethods.h:6321)
(no backtrace available) 
```
I have no idea about this as I'am not using Miniconda. I guess `miniconda3` is your development environment.

2. I mean somethings described [here](https://github.com/pytorch/pytorch/issues/3158#issue-266403375).

By the way,  I found a potential minor flaw in `pytorch_sparse/torch_sparse/matmul.py/` . 
```python3
def matmul(src: SparseTensor, other: Union[torch.Tensor, SparseTensor],
           reduce: str = "sum"):
    if torch.is_tensor(other):
         #This may lead to some problems of dispatching `spmm`  since 
        #torch.is_tensor(torch.sparse_coo_mat) also returns True.
        return spmm(src, other, reduce)
    elif isinstance(other, SparseTensor):
        return spspmm(src, other, reduce)
    else:
        raise ValueError
```

**Comment by rusty1s** [comment]
1.
```
a = np.arange(1, n**2 + 1).reshape(n, n).astype(np.float32)
```
should fix this issue.
2. Fixed in master

**Comment by bwdeng20** [comment]
1. It works! 
2. Actually I was talking about broadcasting sematics doing things like this:
 `spm1[m, n] *(or +, -, /) spm2[1, n] -> spm3[m,n] `

**Comment by rusty1s** [comment]
2. That's also supported, but `spm2` needs to be a regular dense PyTorch tensor.

**Comment by bwdeng20** [comment]
Thx for your excellent works again! I'am looking forward to the new release!
