### ISSUE TITLE
Compatibility between torch.Tensor and SparseTensor

### ISSUE THREAD

**Issue by cqql** [rusty1s/pytorch_sparse#53]
Hey,
how are your plans regarding `SparseTensor`? There seem to be some incompatibilities between the sparse and dense tensors that may be avoidable. For example it would be nice if
- `SparseTensor.size()` would work without arguments and return a `torch.Size`
- `SparseTensor.{dtype,device}` were properties instead of methods (then you could use a sparse tensor directly as an options object)
- sparse tensors could be added to other sparse tensors
I wanted to create a PR but noticed that at least the first two points seem to stem from the fact that the whole of `SparseTensor` is a `torch.jit.script`. Why is that? Does it give a significant performance boost? Do you export `SparseTensor` into no-python environments? Is there a way to make sparse and dense tensors compatible while also keeping the benefits from `torch.jit.script`?

I have recently switched over from the built-in sparse tensors because your `spmm` is very fast and I would like to contribute to make the points in my list possible. Are these things compatible with your goals and should I give it a go? If so, which approach would you prefer/how would you proceed?

Best,
Marten

**Comment by rusty1s** [comment]
Hi and thanks for your interest! You are right that `size`, `dtype`, and `device` has some incompatibilities because of `torch.jit.script`. That does not give any speed-ups in `torch_sparse` though, but one would expect it to give speed-ups when combined in a jitted neural network pipeline. In addition, it is just a nice-to-have feature. I feel that most of those incompatibilities can be reduced once PyTorch has `Union` support.

Addition of sparse tensors that I had in my mind too, but it is quite tricky to implement. I would be fine with a `cusparse` wrapper, but the backward implementation needs to be implemented manually. If you want to work on this, please feel free to do so. At the moment, it is not a top-priority for me.

**Comment by cqql** [comment]
Is the jit the reason why some methods are defined outside of `SparseTensor` and then later assigned such as `SparseTensor.to`? How do you feel about doing the same for other methods to increase the compatibility to dense tensors? I just think it is nice to be able to use the exact same code with both types of tensors.

I have looked into cusparse and I agree that it seems quite involved, so that will probably have to wait for now.

**Comment by rusty1s** [comment]
Yes, defining the methods outside of the class allows us to define pure python functions without jit restrictions. This may be indeed more user-friendly.
