### ISSUE TITLE
New Feature Request: SparseTensor `+(*,-)` SparseTensor

### ISSUE THREAD

**Issue by bwdeng20** [rusty1s/pytorch_sparse#58]
Hi, Matthias Fey! Do you have plan to support basic element-wise arithmetic  such as `+`,`-` and `*` for two `SparseTensor`s with a same shape. Besides, as some element-wise operations, e.g., `add_nnz_`  and `mul_nnz` are already implemented through modifying `SparseTensor.storage._value`, I think other operations such as `log`, `cos` and `abs` can be, with little difficulty, implemented in a similar way . Is there any plan about them?

**Comment by rusty1s** [comment]
Hi, I agree with you that element-wise arithmetic such as +, * should be implemented, but they require computation of union and intersection of sparse indices which is not so trivial on GPU.

For log, cos, ..., operations, I am not sure if this library should really implement these operations (since this would most likely result in replicating all PyTorch functionality). I think it is fine the way it is by just applying the respective PyTorch function to the values of a sparse mat. You can also always add certain functionalities to `SparseTensor` on your own (by following the procedures of `add_nnz`).

**Comment by bwdeng20** [comment]
I am sorry that I can't help you to implement some `.cu` or `cxx` functionality at present. I am going to learn `cpp` and `CUDA`  programming later this year. Perhaps I will be able to provide some help by the time when I have some experiences.

I used to regarded this library as an complete substitute of `torch.sparse` so I want to supplement some funtionality already provided by `torch.sparse`.  Maybe I misunderstanded  your goal but I respect your plan.
